name: Deploy if not a version bump PR
on:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged == true && !contains(github.event.pull_request.labels.*.name, 'Version bump') }}
    steps:
      - uses: actions/checkout@v2
      - run: gh workflow run deploy.yml --ref move-to-github-actions
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_PAT }}
