name: TDR Deploy File Metadata
on:
  workflow_dispatch:
env:
  RUN_NUMBER: ${{ github.run_id }}${{ github.run_attempt }}
  BRANCH_NAME: version-bump-${{ github.run_id }}${{ github.run_attempt }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          ./.github/scripts/deploy_npm.sh ${{ secrets.NPM_TOKEN }}
      - name: Create Pull Request
        run: gh pr create --fill --label 'Version bump'
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_PAT }}
      - name: Send success message
        uses: nationalarchives/tdr-github-actions/.github/actions/slack-send@main
        with:
          message: ":white_check_mark: File metadata has been published"
          slack-url: ${{ secrets.SLACK_WEBHOOK }}
